CREATE DATABASE hoteldb;
-- Connect to hoteldb before running the rest.

-- UserRoles Table
CREATE TABLE user_roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    description VARCHAR(255)
);

-- User Information
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT,
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES user_roles(role_id)
);

-- Countries and States Tables
CREATE TABLE countries (
    country_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(50),
    country_code VARCHAR(10),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE states (
    state_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name VARCHAR(50),
    country_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_states_country
        FOREIGN KEY (country_id) REFERENCES countries(country_id)
);

-- Room Types Master Data
CREATE TABLE room_types (
    room_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50),
    accessibility_features VARCHAR(255),
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP
);

-- Rooms of the Hotel
CREATE TABLE rooms (
    room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(10) UNIQUE,
    room_type_id INT,
    price NUMERIC(10,2),
    bed_type VARCHAR(50),
    view_type VARCHAR(50),
    status VARCHAR(50) CHECK (status IN ('Available', 'Under Maintenance', 'Occupied')),
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP,
    CONSTRAINT fk_rooms_room_type
        FOREIGN KEY (room_type_id) REFERENCES room_types(room_type_id)
);

-- Amenities Available in the hotel
CREATE TABLE amenities (
    amenity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP
);

-- Linking room types with amenities
CREATE TABLE room_amenities (
    room_type_id INT,
    amenity_id INT,
    PRIMARY KEY (room_type_id, amenity_id),
    CONSTRAINT fk_room_amenities_room_type
        FOREIGN KEY (room_type_id) REFERENCES room_types(room_type_id),
    CONSTRAINT fk_room_amenities_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenities(amenity_id)
);

-- The Guests who are going to stay in the hotel
CREATE TABLE guests (
    guest_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    phone VARCHAR(15),
    age_group VARCHAR(20) CHECK (age_group IN ('Adult', 'Child', 'Infant')),
    address VARCHAR(255),
    country_id INT,
    state_id INT,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP,
    CONSTRAINT fk_guests_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_guests_country
        FOREIGN KEY (country_id) REFERENCES countries(country_id),
    CONSTRAINT fk_guests_state
        FOREIGN KEY (state_id) REFERENCES states(state_id)
);

-- Storing Reservation Information
CREATE TABLE reservations (
    reservation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    room_id INT,
    booking_date DATE,
    check_in_date DATE,
    check_out_date DATE,
    number_of_guests INT,
    status VARCHAR(50) CHECK (status IN ('Reserved', 'Checked-in', 'Checked-out', 'Cancelled')),
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP,
    CONSTRAINT fk_reservations_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_reservations_room
        FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT chk_checkout_date
        CHECK (check_out_date > check_in_date)
);

-- Mapping table for guests linked to reservations
CREATE TABLE reservation_guests (
    reservation_guest_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INT,
    guest_id INT,
    CONSTRAINT fk_reservation_guests_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id),
    CONSTRAINT fk_reservation_guests_guest
        FOREIGN KEY (guest_id) REFERENCES guests(guest_id)
);

-- Table for tracking batch payments
CREATE TABLE payment_batches (
    payment_batch_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    payment_date TIMESTAMP,
    total_amount NUMERIC(10,2),
    payment_method VARCHAR(50),
    CONSTRAINT fk_payment_batches_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Individual payments Linked to Reservations and Batch Payment
CREATE TABLE payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INT,
    amount NUMERIC(10,2),
    payment_batch_id INT,
    CONSTRAINT fk_payments_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id),
    CONSTRAINT fk_payments_batch
        FOREIGN KEY (payment_batch_id) REFERENCES payment_batches(payment_batch_id)
);

-- Cancellations tracking with a fee
CREATE TABLE cancellations (
    cancellation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INT,
    cancellation_date TIMESTAMP,
    reason VARCHAR(255),
    cancellation_fee NUMERIC(10,2),
    cancellation_status VARCHAR(50) CHECK (cancellation_status IN ('Pending', 'Approved', 'Denied')),
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    modified_date TIMESTAMP,
    CONSTRAINT fk_cancellations_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id)
);

-- Table for Storing Refund Methods
CREATE TABLE refund_methods (
    method_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE
);

-- Table for tracking Refunds
CREATE TABLE refunds (
    refund_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INT,
    refund_amount NUMERIC(10,2),
    refund_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    refund_reason VARCHAR(255),
    refund_method_id INT,
    processed_by_user_id INT,
    refund_status VARCHAR(50),
    CONSTRAINT fk_refunds_payment
        FOREIGN KEY (payment_id) REFERENCES payments(payment_id),
    CONSTRAINT fk_refunds_method
        FOREIGN KEY (refund_method_id) REFERENCES refund_methods(method_id),
    CONSTRAINT fk_refunds_processed_by
        FOREIGN KEY (processed_by_user_id) REFERENCES users(user_id)
);

-- Feedback Table
CREATE TABLE feedbacks (
    feedback_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INT,
    guest_id INT,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(1000),
    feedback_date TIMESTAMP,
    CONSTRAINT fk_feedbacks_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id),
    CONSTRAINT fk_feedbacks_guest
        FOREIGN KEY (guest_id) REFERENCES guests(guest_id)
);